# Dependencies
# markdown:         kmarkdown
highlighter:      rouge
# Gems
plugins:    [jekyll-paginate]
# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:           "Wei Chen"
tagline:          'Personal Website'
# url:              http://hyde.getpoole.com
baseurl:          https://weihelloworld.github.io/

# author:
#   name:           'Mark Otto'
#   url:            https://twitter.com/mdo

paginate:         5

# Custom vars

